name: backend
description: Back-end do aplicativo de veículos.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.2
  mysql1: ^0.20.0
  bcrypt: ^1.1.3 # Versão compatível com o seu ambiente
  logger: ^1.4.0
